dist: xenial

language: go

go:
  - 1.13.x

git:
  depth: 1

install:
  - go install github.com/hatchify/output

cache:
 directories:
   - $HOME/.cache/go-build
   - $HOME/gopath/pkg/mod
   - $HOME/go/pkg/mod

notifications:
  email: false

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make lint
  - make test
